# Generated by Django 5.2.15 on 2026-07-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_env', models.CharField(blank=True, help_text='sandbox または production。空欄なら.envの値を使用', max_length=20, verbose_name='eBay環境')),
                ('ebay_app_id', models.CharField(blank=True, max_length=200, verbose_name='EBAY_APP_ID')),
                ('ebay_dev_id', models.CharField(blank=True, max_length=200, verbose_name='EBAY_DEV_ID')),
                ('ebay_cert_id', models.CharField(blank=True, max_length=200, verbose_name='EBAY_CERT_ID')),
                ('ebay_auth_token', models.TextField(blank=True, verbose_name='EBAY_AUTH_TOKEN')),
                ('gemini_api_key', models.CharField(blank=True, max_length=300, verbose_name='Gemini APIキー')),
                ('manual_payment_profiles', models.JSONField(blank=True, default=list, verbose_name='Payment Policy (手動登録)')),
                ('manual_shipping_profiles', models.JSONField(blank=True, default=list, verbose_name='Shipping Policy (手動登録)')),
                ('manual_return_profiles', models.JSONField(blank=True, default=list, verbose_name='Return Policy (手動登録)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'アプリ設定',
                'verbose_name_plural': 'アプリ設定',
            },
        ),
    ]
