# Generated by Django 5.2.15 on 2026-07-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='ItemID')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='SKU')),
                ('custom_label', models.CharField(blank=True, max_length=100, verbose_name='カスタムラベル')),
                ('title_ja', models.CharField(blank=True, max_length=300, verbose_name='タイトル(日本語)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='タイトル(英語)')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='通貨')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='販売価格')),
                ('best_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Best Offer')),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='送料')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('watch_count', models.PositiveIntegerField(default=0, verbose_name='watch')),
                ('status', models.CharField(choices=[('販売中', '販売中'), ('確認不可', '確認不可'), ('売り切れ', '売り切れ'), ('出品準備中', '出品準備中'), ('終了', '終了')], default='出品準備中', max_length=20, verbose_name='ステータス')),
                ('route', models.CharField(choices=[('メルカリ', 'メルカリ'), ('Amazon', 'Amazon'), ('その他', 'その他')], default='その他', max_length=20, verbose_name='ルート')),
                ('result_note', models.CharField(blank=True, max_length=200, verbose_name='結果')),
                ('category_id', models.CharField(blank=True, max_length=32, verbose_name='CategoryID')),
                ('category_name', models.CharField(blank=True, max_length=200, verbose_name='Category Name')),
                ('condition_id', models.CharField(blank=True, max_length=16, verbose_name='ConditionID')),
                ('condition_description', models.TextField(blank=True, verbose_name='状態説明')),
                ('brand', models.CharField(blank=True, max_length=200, verbose_name='Brand')),
                ('upc', models.CharField(blank=True, max_length=64, verbose_name='UPC')),
                ('mpn', models.CharField(blank=True, max_length=64, verbose_name='MPN')),
                ('item_specifics', models.JSONField(blank=True, default=list, verbose_name='Item Specifics')),
                ('image_urls', models.JSONField(blank=True, default=list, verbose_name='画像URL')),
                ('description_ja', models.TextField(blank=True, verbose_name='詳細説明(日本語)')),
                ('description_html', models.TextField(blank=True, verbose_name='HTML(英語)')),
                ('supply_url', models.URLField(blank=True, max_length=500, verbose_name='仕入れ元URL')),
                ('supply_price_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='price上限')),
                ('supply_memo', models.CharField(blank=True, max_length=300, verbose_name='メモ')),
                ('additional_skus', models.JSONField(blank=True, default=list, verbose_name='追加SKU')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='仕入価格')),
                ('fee_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='手数料(%)')),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='為替')),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='送料等')),
                ('is_active', models.BooleanField(default=True, verbose_name='出品中')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='最終取得日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '出品',
                'verbose_name_plural': '出品一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
