# Generated by Django 5.2.15 on 2026-07-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='payment_profile_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='Payment Policy ID'),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_profile_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Payment Policy名'),
        ),
        migrations.AddField(
            model_name='listing',
            name='return_profile_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='Return Policy ID'),
        ),
        migrations.AddField(
            model_name='listing',
            name='return_profile_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Return Policy名'),
        ),
        migrations.AddField(
            model_name='listing',
            name='shipping_profile_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='Shipping Policy ID'),
        ),
        migrations.AddField(
            model_name='listing',
            name='shipping_profile_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Shipping Policy名'),
        ),
    ]
