# Generated by Django 5.2.15 on 2026-07-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_payment_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='item_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='ItemID'),
        ),
    ]
