# Generated by Django 5.2.15 on 2026-07-03 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercariLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercari_url', models.URLField(max_length=500, verbose_name='メルカリURL')),
                ('mercari_sku', models.CharField(blank=True, max_length=100, verbose_name='メルカリSKU/管理番号')),
                ('last_stock_status', models.CharField(choices=[('不明', '不明'), ('在庫あり', '在庫あり'), ('売り切れ', '売り切れ')], default='不明', max_length=10, verbose_name='在庫状況')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='最終確認日時')),
                ('auto_delist_enabled', models.BooleanField(default=True, verbose_name='自動取り下げ有効')),
                ('delisted_at', models.DateTimeField(blank=True, null=True, verbose_name='取り下げ日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mercari_link', to='listings.listing')),
            ],
            options={
                'verbose_name': 'メルカリ紐づけ',
                'verbose_name_plural': 'メルカリ紐づけ一覧',
            },
        ),
        migrations.CreateModel(
            name='StockCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10, verbose_name='結果ステータス')),
                ('action_taken', models.CharField(blank=True, max_length=50, verbose_name='実施アクション')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('mercari_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mercari_link.mercarilink')),
            ],
            options={
                'verbose_name': '在庫確認ログ',
                'verbose_name_plural': '在庫確認ログ一覧',
                'ordering': ['-checked_at'],
            },
        ),
    ]
